language: node_js
node_js: '10'
cache:
  yarn: true
env:
  global:
    - FORCE_COLOR=1
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
jobs:
  include:
    - stage: build
      install: skip
      script:
        - ./ci
stages:
  - build
branches:
  only:
    - master
