language: node_js
node_js: '10'
cache:
  yarn: true
env:
  global:
    - FORCE_COLOR=1
jobs:
  include:
    - stage: build
      install: skip
      script:
        - ./ci
stages:
  - build
branches:
  only:
    - master
