language: node_js
node_js: '10'
cache:
  directories:
    - ~/.npm
env:
  global:
    - FORCE_COLOR=1
jobs:
  include:
    - stage: test
      script:
        - npm run prettier
        - npm run tslint
        - npm run build
stages:
  - test
branches:
  only:
    - master
