#!/usr/bin/env bash

set -ex

yarn -s --frozen-lockfile
yarn -s run prettier-check

pushd package
yarn -s --frozen-lockfile
yarn -s run build
yarn -s run cover
bash <(curl -s https://codecov.io/bash)
popd

pushd template
yarn -s --frozen-lockfile
yarn -s run typecheck
yarn -s run build
popd
