#!/usr/bin/env bash

set -ex

yarn -s
git diff --exit-code
yarn -s run prettier-check

pushd package
yarn -s
git diff --exit-code
yarn -s run build
yarn -s run test
popd

pushd template
yarn -s
git diff --exit-code
yarn -s run typecheck
yarn -s run build
popd
