/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Settings {
    /**
     * The LightStep project token to use for tracing.
     */
    'lightstep.token'?: string | null
    /**
     * The Sourcegraph endpoint the TypeScript server should use
     */
    'typescript.sourcegraphUrl'?: string
    /**
     * Whether to enable TypeScript code intelligence. (Default: true)
     */
    'typescript.enable'?: boolean
    /**
     * Whether to report progress while fetching sources, installing dependencies etc. (Default: true)
     */
    'typescript.progress'?: boolean
    /**
     * Whether to show compile errors on lines (Default: false)
     */
    'typescript.diagnostics.enable'?: boolean
    /**
     * Settings to be written into an npmrc in key/value format. Can be used to specify custom registries and tokens.
     */
    'typescript.npmrc'?: {
        [k: string]: any
    }
    /**
     * Whether to restart the language server after dependencies were installed (default true)
     */
    'typescript.restartAfterDependencyInstallation'?: boolean
    /**
     * The WebSocket language server to connect to
     */
    'typescript.serverUrl'?: string
    /**
     * The access token for the language server to use to fetch files from the Sourcegraph API. The extension will create this token and save it in your settings automatically.
     */
    'typescript.accessToken'?: string
    /**
     * The log level to pass to the TypeScript language server. Logs will be forwarded to the browser console with the prefix [langserver].
     */
    'typescript.langserver.log'?: false | 'log' | 'info' | 'warn' | 'error'
    /**
     * The log level to pass to tsserver. Logs will be forwarded to the browser console with the prefix [tsserver].
     */
    'typescript.tsserver.log'?:
        | false
        | 'terse'
        | 'normal'
        | 'requestTime'
        | 'verbose'
    /**
     * Whether to use pre-computed LSIF data for code intelligence (such as hovers, definitions, and references). See https://docs.sourcegraph.com/user/code_intelligence/lsif.
     */
    'codeIntel.lsif'?: boolean
}
