import * as sourcegraph from 'sourcegraph'

const linkURL = 'https://docs.sourcegraph.com/code_intelligence/explanations/precise_code_intelligence'

function makeSummary(message: string, ctaMessage: string): sourcegraph.MarkupContent {
    return { kind: sourcegraph.MarkupKind.Markdown, value: `${message} [${ctaMessage}](${linkURL})` }
}

function makeBadge(lines: string[]): sourcegraph.BadgeAttachmentRenderOptions {
    return { kind: 'info', linkURL, hoverMessage: lines.join(' ') }
}

//
// LSIF

const lsifBadge = makeBadge([
    "This hover data comes from a pre-computed semantic index of this project's source.",
    'Click to learn how to add this capability to all of your projects!',
])

const partialBadge = makeBadge([
    'It looks like this symbol is defined in another repository that does not have a pre-computed semantic index.',
    'Click to learn how to make these results precise by enabling semantic indexing for that project.',
])

// note: used to have type: 'LSIFAvailableNoCaveat'
export const lsif: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Semantic result.', 'Learn more.'),
    badge: lsifBadge,
}

// note: used to have type: 'LSIFAvailableNoCaveat'
export const lsifPartialHoverOnly: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Partial semantic result: Go to definition may be imprecise.', 'Learn more.'),
    badge: partialBadge,
}

// note: used to have type: 'LSIFAvailableNoCaveat'
export const lsifPartialDefinitionOnly: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Partial semantic result: this hover text may be imprecise.', 'Learn more.'),
    badge: partialBadge,
}

//
// LSP

const lspBadge = makeBadge([
    'This hover data comes from a language server running in the cloud.',
    'Click to learn how to improve the reliability of this result by enabling semantic indexing.',
])

export const lsp: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Language server result.', 'Get LSIF.'),
    badge: lspBadge,
}

//
// Search

const robustSupportBadge = makeBadge([
    'This hover data is generated by a heuristic text-based search.',
    'Click to learn how to make these results precise by enabling semantic indexing for this project.',
])

const experimentalSupportBadge = makeBadge([
    'This hover data is generated by a heuristic text-based search.',
    "Existing semantic indexers for this language aren't totally robust yet, but you can click here to learn how to give them a try.",
])

export const searchLSIFSupportRobust: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Search-based result.', 'Get semantics.'),
    badge: robustSupportBadge,
}

// note: used to have type: 'SearchResultExperimentalLSIFSupport'
export const searchLSIFSupportExperimental: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Search-based result.', 'Learn more.'),
    badge: experimentalSupportBadge,
}

// note: used to have type: 'SearchResultNoLSIFSupport'
export const searchLSIFSupportNone: sourcegraph.Badged<sourcegraph.HoverAlert> = {
    summary: makeSummary('Search-based result.', 'Learn more.'),
}
